@startuml usecase_manage_system
!include ./astah_style.puml
left to right direction

title DecomposeManageSystem

actor "SystemAdministrator" as SystemAdministrator

rectangle "ImportAssignmentSystem" {
  usecase "ManageSystem" as ManageSystem
  usecase "ManageUsersAndActorRoles" as ManageUsersAndActorRoles
  usecase "ManageSharedMasterData" as ManageSharedMasterData
  usecase "ViewCrossDepartmentOperationLogs" as ViewCrossDepartmentOperationLogs
  usecase "BackupAndRestoreBusinessData" as BackupAndRestoreBusinessData
}

SystemAdministrator --> ManageSystem
ManageSystem ..> ManageUsersAndActorRoles
ManageSystem ..> ManageSharedMasterData
ManageSystem ..> ViewCrossDepartmentOperationLogs
ManageSystem ..> BackupAndRestoreBusinessData

@enduml
